#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  May 02, 2023 07:55:03 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #d9d9d9
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 794x644+854+393
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame "$top.tFr47" \
        -borderwidth 2 -relief groove -width 125 -height 75 
    vTcl:DefineAlias "$top.tFr47" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.tFr47
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_3_0.tLa48" \
        -text "TNotebook Tab Position" -width 741 -height 75 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.tLa48
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa47" \
        -variable "selectedButton" -command "on_TRB_Click" -text "NW" \
        -compound left 
    vTcl:DefineAlias "$site_4_0.tRa47" "TRadiobutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa48" \
        -variable "selectedButton" -value "2" -command "on_TRB_Click" \
        -text "N" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa48" "TRadiobutton2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa49" \
        -variable "selectedButton" -value "3" -command "on_TRB_Click" \
        -text "NE" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa49" "TRadiobutton3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa50" \
        -variable "selectedButton" -value "4" -command "on_TRB_Click" \
        -text "EN" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa50" "TRadiobutton4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa51" \
        -variable "selectedButton" -value "5" -command "on_TRB_Click" \
        -text "E" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa51" "TRadiobutton5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa52" \
        -variable "selectedButton" -value "6" -command "on_TRB_Click" \
        -text "ES" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa52" "TRadiobutton6" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa53" \
        -variable "selectedButton" -value "7" -command "on_TRB_Click" \
        -text "SE" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa53" "TRadiobutton7" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa54" \
        -variable "selectedButton" -value "8" -command "on_TRB_Click" \
        -text "S" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa54" "TRadiobutton8" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa55" \
        -variable "selectedButton" -value "9" -command "on_TRB_Click" \
        -text "SW" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa55" "TRadiobutton9" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa56" \
        -variable "selectedButton" -value "10" -command "on_TRB_Click" \
        -text "WS" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa56" "TRadiobutton10" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa57" \
        -variable "selectedButton" -value "11" -command "on_TRB_Click" \
        -text "W" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa57" "TRadiobutton11" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa58" \
        -variable "selectedButton" -value "12" -command "on_TRB_Click" \
        -text "WN" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa58" "TRadiobutton12" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.tRa47 \
        -in $site_4_0 -x 4 -y 27 -width 57 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tRa48 \
        -in $site_4_0 -x 65 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa49 \
        -in $site_4_0 -x 126 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa50 \
        -in $site_4_0 -x 187 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa51 \
        -in $site_4_0 -x 248 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa52 \
        -in $site_4_0 -x 309 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa53 \
        -in $site_4_0 -x 370 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa54 \
        -in $site_4_0 -x 431 -y 27 -width 57 -relwidth 0 -height 0 \
        -relheight 0.28 -anchor nw -bordermode ignore 
    place $site_4_0.tRa55 \
        -in $site_4_0 -x 479 -y 27 -width 57 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tRa56 \
        -in $site_4_0 -x 541 -y 27 -width 57 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tRa57 \
        -in $site_4_0 -x 614 -y 27 -width 57 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_4_0.tRa58 \
        -in $site_4_0 -x 675 -y 27 -width 57 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook "$site_3_0.tNo49" \
        -width 542 -height 316 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo49" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    frame "$site_3_0.tNo49.t0" \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo49.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_3_0.tNo49 add $site_3_0.tNo49.t0 \
        -padding 0 -sticky nsew -state normal -text "Standard Tk Widgets" \
        -image {} -compound left -underline -1 
    set site_5_0  $site_3_0.tNo49.t0
    label "$site_5_0.lab50" \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -font "-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Just a Tk Label Widget" 
    vTcl:DefineAlias "$site_5_0.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_5_0.tLa47" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor center \
        -justify center -textvariable "::TLabTab1" -compound left 
    vTcl:DefineAlias "$site_5_0.tLa47" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_0.lab50 \
        -in $site_5_0 -x 140 -y 60 -width 0 -relwidth 0.461 -height 0 \
        -relheight 0.141 -anchor nw -bordermode ignore 
    place $site_5_0.tLa47 \
        -in $site_5_0 -x 130 -y 150 -width 262 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$site_3_0.tNo49.t1" \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo49.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_3_0.tNo49 add $site_3_0.tNo49.t1 \
        -padding 0 -sticky nsew -state normal -text "ttk Widgets" -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo49.t1
    ttk::label "$site_5_1.tLa48" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -textvariable "::TLabTab2" -compound left 
    vTcl:DefineAlias "$site_5_1.tLa48" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_1.tLa48 \
        -in $site_5_1 -x 30 -y 30 -width 302 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$site_3_0.tNo49.t2" \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo49.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_3_0.tNo49 add $site_3_0.tNo49.t2 \
        -padding 0 -sticky nsew -state normal -text "Enhanced Widgets" \
        -image {} -compound left -underline -1 
    set site_5_2  $site_3_0.tNo49.t2
    ttk::label "$site_5_2.tLa49" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -textvariable "::TLabTab3" -compound left 
    vTcl:DefineAlias "$site_5_2.tLa49" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_2.tLa49 \
        -in $site_5_2 -x 160 -y 100 -width 242 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$site_3_0.tNo49.t3" \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo49.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_3_0.tNo49 add $site_3_0.tNo49.t3 \
        -padding 0 -sticky nsew -state normal -text "Extra Stuff" -image {} \
        -compound left -underline -1 
    set site_5_3  $site_3_0.tNo49.t3
    label "$site_5_3.lab49" \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -font "-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Just a widget" 
    vTcl:DefineAlias "$site_5_3.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_5_3.tLa50" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -textvariable "::TLabTab4" -compound left 
    vTcl:DefineAlias "$site_5_3.tLa50" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_3.lab49 \
        -in $site_5_3 -x 140 -y 60 -width 0 -relwidth 0.387 -height 0 \
        -relheight 0.107 -anchor nw -bordermode ignore 
    place $site_5_3.tLa50 \
        -in $site_5_3 -x 70 -y 140 -width 362 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$site_3_0.tBu51" \
        -command "on_btnExit" -takefocus {} -text "Exit" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu51" "TButton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 0 -relx 0.02 -y 0 -rely 0.116 -width 0 \
        -relwidth 0.878 -height 0 -relheight 0.116 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tNo49 \
        -in $site_3_0 -x 120 -y 200 -width 0 -relwidth 0.642 -height 0 \
        -relheight 0.491 -anchor nw -bordermode ignore 
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 670 -y 20 -width 103 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr47 \
        -in $top -x 0 -y 0 -width 863 -relwidth 0 -height 644 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

